server {
    listen 80;
    server_name srv1427612.hstgr.cloud;

    root /usr/share/nginx/html;
    index index.html;

    location /cc/ {
        try_files $uri $uri/ /cc/index.html;
    }

    location / {
        return 301 /cc/;
    }
}
